/**
 * Realistic Chrome 130 (macOS) headers — what Shopee/Lazada anti-bot looks
 * for before challenging. Generated by inspecting the actual fetch headers
 * the desktop site sends. Keep in sync when Chrome's UA bumps versions.
 *
 * Why no random-rotation: this isn't scraping at scale, it's an opted-in
 * import the user explicitly triggered for their own catalogue. We just
 * need to look enough like a real browser that the public mobile-web API
 * doesn't 403 us.
 */
export const REAL_CHROME_HEADERS = {
  "User-Agent":
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
  "Accept":
    "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
  "Accept-Language": "th-TH,th;q=0.9,en-US;q=0.8,en;q=0.7",
  "Sec-Ch-Ua": '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
  "Sec-Ch-Ua-Mobile": "?0",
  "Sec-Ch-Ua-Platform": '"macOS"',
  "Sec-Fetch-Dest": "document",
  "Sec-Fetch-Mode": "navigate",
  "Sec-Fetch-Site": "none",
  "Sec-Fetch-User": "?1",
  "Upgrade-Insecure-Requests": "1",
};

/**
 * Variant for Shopee's mobile-web JSON API. Shopee specifically checks
 * `X-API-SOURCE: pc` + a few language headers before serving the
 * `/api/v4/item/get` payload. Without them the response is HTML.
 */
export const SHOPEE_API_HEADERS = {
  ...REAL_CHROME_HEADERS,
  "Accept": "application/json, text/plain, */*",
  "X-API-SOURCE": "pc",
  "X-Requested-With": "XMLHttpRequest",
  "X-Shopee-Language": "th",
  "Sec-Fetch-Dest": "empty",
  "Sec-Fetch-Mode": "cors",
  "Sec-Fetch-Site": "same-origin",
};
